from eye_catch.links.makino_maria import MAKINO_MARIA_LINKS
from eye_catch.links.sakurai_rio import SAKURAI_RIO_LINKS

from eye_catch.links.ise_layla import ISE_LAYLA_LINKS
from eye_catch.links.kawana_rin import KAWANA_RIN_LINKS

from eye_catch.links.nishida_shiori import NISHIDA_SHIORI_LINKS
from eye_catch.links.maeda_kokoro import MAEDA_KOKORO_LINKS
from eye_catch.links.satoyoshi_utano import SATOYOSHI_UTANO_LINKS

MOVIE_LINK_DICT = {
    "石田亜佑美": [{'title': '', 'embed_link': ''}],
    "生田衣梨奈": [{'title': '', 'embed_link': ''}],
    "小田さくら": [{'title': '', 'embed_link': ''}],
    "野中美希": [{'title': '', 'embed_link': ''}],
    "牧野真莉愛": MAKINO_MARIA_LINKS,
    "横山玲奈": [{'title': '', 'embed_link': ''}],
    "羽賀朱音": [{'title': '', 'embed_link': ''}],
    "北川莉央": [{'title': '', 'embed_link': ''}],
    "岡村ほまれ": [{'title': '', 'embed_link': ''}],
    "山﨑愛生": [{'title': '', 'embed_link': ''}],
    "櫻井梨央": SAKURAI_RIO_LINKS,
    "井上春華": [{'title': '', 'embed_link': ''}],
    "弓桁朱琴": [{'title': '', 'embed_link': ''}],

    "川村文乃": [{'title': '', 'embed_link': ''}],
    "上國料萌衣": [{'title': '', 'embed_link': ''}],
    "佐々木莉佳子": [{'title': '', 'embed_link': ''}],
    "川名凜": KAWANA_RIN_LINKS,
    "伊勢鈴蘭": ISE_LAYLA_LINKS,
    "為永幸音": [{'title': '', 'embed_link': ''}],
    "橋迫鈴": [{'title': '', 'embed_link': ''}],
    "平山遊季": [{'title': '', 'embed_link': ''}],
    "下井谷幸穂": [{'title': '', 'embed_link': ''}],
    "松本わかな": [{'title': '', 'embed_link': ''}],
    "後藤花": [{'title': '', 'embed_link': ''}],

    "植村あかり": [{'title': '', 'embed_link': ''}],
    "段原瑠々": [{'title': '', 'embed_link': ''}],
    "井上玲音": [{'title': '', 'embed_link': ''}],
    "有澤一華": [{'title': '', 'embed_link': ''}],
    "石山咲良": [{'title': '', 'embed_link': ''}],
    "工藤由愛": [{'title': '', 'embed_link': ''}],
    "松永里愛": [{'title': '', 'embed_link': ''}],
    "入江里咲": [{'title': '', 'embed_link': ''}],
    "江端妃咲": [{'title': '', 'embed_link': ''}],
    "川嶋美楓": [{'title': '', 'embed_link': ''}],
    "遠藤彩加里": [{'title': '', 'embed_link': ''}],

    "新沼希空": [{'title': '', 'embed_link': ''}],
    "谷本安美": [{'title': '', 'embed_link': ''}],
    "小野瑞歩": [{'title': '', 'embed_link': ''}],
    "小野田紗栞": [{'title': '', 'embed_link': ''}],
    "秋山眞緒": [{'title': '', 'embed_link': ''}],
    "河西結心": [{'title': '', 'embed_link': ''}],
    "八木栞": [{'title': '', 'embed_link': ''}],
    "福田真琳": [{'title': '', 'embed_link': ''}],
    "豫風瑠乃": [{'title': '', 'embed_link': ''}],
    "石井泉羽": [{'title': '', 'embed_link': ''}],
    "村田結生": [{'title': '', 'embed_link': ''}],
    "土居楓奏": [{'title': '', 'embed_link': ''}],

    "一岡伶奈": [{'title': '', 'embed_link': ''}],
    "島倉りか": [{'title': '', 'embed_link': ''}],
    "西田汐里": NISHIDA_SHIORI_LINKS,
    "江口紗耶": [{'title': '', 'embed_link': ''}],
    "高瀬くるみ": [{'title': '', 'embed_link': ''}],
    "前田こころ": MAEDA_KOKORO_LINKS,
    "山﨑夢羽": [{'title': '', 'embed_link': ''}],
    "岡村美波": [{'title': '', 'embed_link': ''}],
    "清野桃々姫": [{'title': '', 'embed_link': ''}],
    "平井美葉": [{'title': '', 'embed_link': ''}],
    "小林萌花": [{'title': '', 'embed_link': ''}],
    "里吉うたの": SATOYOSHI_UTANO_LINKS,
    "斉藤円香": [{'title': '', 'embed_link': ''}],
    "広本瑠璃": [{'title': '', 'embed_link': ''}],
    "石栗奏美": [{'title': '', 'embed_link': ''}],
    "米村姫良々": [{'title': '', 'embed_link': ''}],
    "窪田七海": [{'title': '', 'embed_link': ''}],
    "田代すみれ": [{'title': '', 'embed_link': ''}],
    "中山夏月姫": [{'title': '', 'embed_link': ''}],
    "西﨑美空": [{'title': '', 'embed_link': ''}],
    "北原もも": [{'title': '', 'embed_link': ''}],
    "筒井澪心": [{'title': '', 'embed_link': ''}],
}
