SATOYOSHI_UTANO_LINKS = [
    {'title': "24:14_いつも通りの君ならきっと大丈夫", "embed_link": "https://www.youtube.com/embed/J7i9s17-WHw?si=T7fi8N771X0iLwG3&amp;start=1452"},
    {'title': "32:24_私はアクセサリーが好き。あなたの好きなものはなに？", "embed_link": "https://www.youtube.com/embed/mprgk-k1X6w?si=GOmcD3KvOp7SdXIx&amp;start=1943"},
    {'title': "00:00_いつもお仕事お疲れ様!", "embed_link": "https://www.youtube.com/embed/PnsWSvKVGfg?si=oTBtWmJ0z2wLXUK5&amp;start=3"},
    {'title': "12:02_すご～く好き", "embed_link": "https://www.youtube.com/embed/vKJ_WeCIlPI?si=yB5cnZLSMKQ7ooZa&amp;start=722"},
    {'title': "20:51_楽しんでる？続きも見てね！", "embed_link": "https://www.youtube.com/embed/LouwRIDAJQw?si=Hn5W6t530sfBF3kl&amp;start=1252"},
    {'title': "23:56_がんばっているあなたが好きです", "embed_link": "https://www.youtube.com/embed/--zPZQdGol0?si=1S_hjAeqLKYIEOrL&amp;start=1436"},
    {'title': "13:06_何事もやってみないとわかんないよね", "embed_link": "https://www.youtube.com/embed/aUwADFVykS0?si=2DvuFExKfkf21MHr&amp;start=787"},
    {'title': '33:34_お仕事大変そうだね。一息ついてね。', 'embed_link': "https://www.youtube.com/embed/xXzni7T7nyk?si=vNZj2UfbsLOGlTCk&amp;start=2014"},
    {'title': '03:55_そのままの調子ならきっと大丈夫', 'embed_link': "https://www.youtube.com/embed/vhwKqkdhk_g?si=70JWmiD1fqUtTCb3&amp;start=235"},
    {'title': '20:46_今日は...ゆっくり過ごそうよ', 'embed_link': "https://www.youtube.com/embed/-KeieTh1sRQ?si=-Mwy-WHQKD3A2ou9&amp;start=1246"},
    {'title': '19:44_あなたが頑張っていること、私は知っているよ', 'embed_link': "https://www.youtube.com/embed/YI9BNNe_zxo?si=VrPkIkL4_Ut9oLq9&amp;start=1184"},
    {'title': '22:56_楽しんでいてくれたら私もうれしいなぁ', 'embed_link': "https://www.youtube.com/embed/IGtuvnpaXhk?si=f6IsBsMaIF6uVHEp&amp;start=1376"},
    {'title': '31:28_君なら出来る！', 'embed_link': "https://www.youtube.com/embed/GVrt0_bY0Ik?si=LpxoCVimu3eGeoLV&amp;start=1888"},
    {'title': '15:26_あなたのお陰で私も頑張れる', 'embed_link': "https://www.youtube.com/embed/TQG5mykaLlU?si=rMM49GNGWs8siUqi&amp;start=926"},
    {'title': '34:07_明日も頑張りましょう', 'embed_link': "https://www.youtube.com/embed/42J0ik5qRl8?si=3jxEQSuNTnMMWuh_&amp;start=2047"},
    {'title': '07_30_一緒にがんばろう', 'embed_link': "https://www.youtube.com/embed/u4N9Km8_mpo?si=gulc7jtBysxOQ_FG&amp;start=450"},
    {'title': '04:50_あなたの頑張っている姿、私は結構好きだな', 'embed_link': "https://www.youtube.com/embed/HGX25NWDUjs?si=3Flcx_eQPv1wK0Fd&amp;start=290"},
    {'title': '21:19_あなたのお陰で私も頑張れる', 'embed_link': "https://www.youtube.com/embed/tL_0RHW-XrM?si=oFK60TboDBjOCNod&amp;start=1399"},
    {'title': '12:05_最近頑張りすぎてない？無理は禁物だよ', 'embed_link': "https://www.youtube.com/embed/3mkYRziHNbM?si=BtNSZh3JkBKsBwnH&amp;start=725"},
    {'title': '25:36_どんな時も応援してるよ', 'embed_link': "https://www.youtube.com/embed/UfrOKYG6lEI?si=NFuO4mUdVLpdpoSe&amp;start=1536"},
    {'title': '00:01_お待たせ始まるよ', 'embed_link': "https://www.youtube.com/embed/aHcXd_7zfi0?si=wCLno1y3dC4MxOMz&amp;start=1"},
    {'title': '10:38_じっくり行こうよ', 'embed_link': "https://www.youtube.com/embed/XlfBpM9Py9M?si=CWW37lec-GYZHdhY&amp;start=638"},
    {'title': '26:44_見てくれありがとう', 'embed_link': "https://www.youtube.com/embed/uJe7EGDhq4k?si=c28RouXF1VK5Mh28&amp;start=1604"},
    {'title': '07:20_今日はゆっくり過ごそうよ', 'embed_link': "https://www.youtube.com/embed/5FYyZ7FaQTo?si=uJ1HRYuQL5yPvLph&amp;start=440"},
    {'title': '28:35_あなたが頑張っていること、私は知っているよ', 'embed_link': "https://www.youtube.com/embed/eIFsWmqlRLY?si=KJuFC1eyR6BP93Sd&amp;start=1715"},
]
